defaults:
  - writer: wandb
  - datasets: inference_clean
  - transforms: basic
  - _self_
trainer:
  show_examples: 6
  sample_rate: ${transforms.instance_transforms.train.get_spectrogram.sample_rate}
  save_dir: save
  override: True
